// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SCDH.Data;

#nullable disable

namespace SCDH.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("SCDH.Models.ContratoHabitacional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CpfCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroContrato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorImovel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contratos");
                });
#pragma warning restore 612, 618
        }
    }
}
